README.rst
There is no '&allow-other-keys&rest' keyword and it is treated as
normal argument. And '&rest' keyword should be declared before '&key'
keyword.
=> Correct arguments in error callback

request.el
`request--consume-100-continue` may fail under the following conditions.
1. curl posts more than 1024 byte data. (it will add header `Expect: 100-continue`)
- http://d.hatena.ne.jp/tokuhy/20091202/1259766797
2. curl process-coding-system is `*-dos`.
Error example:
```emacs-lisp
(let* ((byte 1025)
(request-backend 'curl)
(request-message-level 'debug)
(default-process-coding-system '(undecided-dos . undecided-dos)))
(request "http://httpbin.org/post"
:type "POST"
:data (with-output-to-string
(dotimes (_ byte)
(princ ".")))
:success #'ignore))
```
Message log:
```
;;; *Message* 
REQUEST [debug] REQUEST
REQUEST [debug] Run: curl --silent --include --location --compressed --cookie curl-cookie-jar --cookie-jar curl-cookie-jar --write-out \n(:num-redirects %{num_redirects} :url-effective …
```
=> Specify curl process encoding

request.el
This is related to #35.
CC: @Silex
Sample code is here.
```lisp
(request
"http:/hello.txt"
:unix-socket "/tmp/app.sock"
:parser (lambda () (buffer-string))
:success (cl-function
(lambda (&key data &allow-other-keys)
(message "Got: %s" data))))
```
=> Support Unix socket for curl backend

request.el
When the server errors, there might still something be to parse from the response. This patch removes a check that prevented to parse the response on server error.
Check also the comment a few lines above the change, which indicates that response should be read even if server errors.
=> Try to parse response also when server errored

request.el
Because ignore-errors ignore all errors.
This is related to #53
=> Use noerror argument instead of ignore-errors

request.el
Writing request data with utf8 chars to a tempfile does not work anymore since https://github.com/tkf/emacs-request/commit/6e039bf
See also: https://github.com/abingham/emacs-ycmd/issues/387
This patch fixes writing the tempfile.
=> Fix writing curl request data to tempfile which includes utf8 chars

.travis.yml, README.rst, request.el
And remove workaround code for older Emacs. All of them are applied on
Emacs 24.4 or higher versions.
=> Drop older emacs support for maintenance

.travis.yml
This pull request updates the build matrix in .travis.yml to include more recent Emacs releases.
~~Along the way I also had to introduce an additional set of configuration to work around what seems to be a malformed TLS certificate[1] on https://elpa.gnu.org. I first ran into this issue in the clojure-emacs/cider project[2] and used the same workaround in that project.~~
~~[1] https://lists.gnu.org/archive/html/emacs-devel/2018-02/msg00142.html~~
~~[2] https://github.com/clojure-emacs/cider/issues/2129~~
=> Update Travis CI build matrix

_sources/index.txt, index.html, manual.html
The cl-lib versions are aliases, but seem to be preferred these days. This also makes the github pages docs consistent with the readme.
=> (github pages) Replace references to function* and defun* with cl-lib versions

tests/request-testing.el
Python 3 is the default on most system in these days. But testserver.py
is still uses deprecated Python 2 syntax (print as keyword).
Fixes this issue on Arch Linux:
```
File "testserver.py", line 116
print port
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(port)?
```
=> Use Python 2 for tests if available

request.el
Emacs 26 added two new required arguments to
tramp-make-tramp-file-name. Additionally, the method part of remote file
names is mandatory.
Also ensure request--make-temp-file creates temporary files in the
temporary folder on the remote host (instead of default-directory).
=> Don't use tramp-make-tramp-file-name function

.travis.yml, Makefile, request.el, tests/test-request.el
User louietan reports sentinel :after advice never executes despite the sentinel process itself executing.
It may have been working previously because `request--curl-callback` was
a compiled function.  If uncompiled, (process-sentinel proc) is a symbol and cannot be add-functioned!
Closes #132
=> Synchronous request deadlocks

request.el
As `request.el` is lexical-binding true, the default-value of
`buffer-file-coding-system` remained unchanged, and we are plunged to
`select-safe-coding-system-interactively`.
Explicitly `setf` the generalized variable `(default-value
'buffer-file-coding-system)`.
Bug reported in kidd/org-gcal.el#41
=> buffer-file-coding-system is not special

request.el
User louietan reports continued deadlock under `synch :t` whereby
[process.c](https://github.com/emacs-mirror/emacs/blob/96dd0196c28bc36779584e47fffcca433c9309cd/src/process.c#L5222) repeatedly detects a "ready" read filedescriptor, and consequently never calls
`status_notify()` to flush the semaphore.
It's unclear where the pending filedescriptor originates so we change the
call to `accept-process-output` to read all file descriptors rather than just the curl.
Attempt #132.
=> Synchronous deadlock second fix

.travis.yml, README.rst, request.el, tests/request-testing.el
Under auto-revert, should the inotify disallow
`wait_reading_process_output` (process.c in emacs source) from calling
status_notify() then kill it.
cf #132
=> Kill inotify if `:sync t` hangs

README.rst, request.el
Just remove the notify descriptor, do the synchronous curl, then
restore the descriptor.
=> Better fix for #140

tests/test-request.el
Otherwise, the byte compiler complains with errors like this:
```
In toplevel form:
third_party/elisp/request/tests/test-request.el:188:1:Error: Unused lexical argument `args'
```
You can tell the byte compiler the variable is unused by giving it a name starting with an underscore (`_`) ([manual](https://www.gnu.org/software/emacs/manual/html_node/elisp/Using-Lexical-Binding.html#Using-Lexical-Binding)).
=> Rename unused arguments to start with underscore

request.el
Shamelessly taking code from
https://github.com/skeeto/elfeed/commit/40d3463ca2c4380d2d9aaf79b0ad8583f464d81b to fix `request-curl` compression detection.
This also fix #111
=> Dynamically enable/disable --compressed curl option

Makefile, request.el
the github continuous-integration/travis-ci/push will have an unpopulated
TRAVIS_PULL_REQUEST_SLUG and TRAVIS_PULL_REQUEST_BRANCH.
In this case we should set repo to TRAVIS_REPO_SLUG.
M. Engdegard has fixed auto-revert-notify-rm-watch in emacs-27.
=> travis merge pull request to master

request.el
In Emacs 27, auto-revert-notify-watch-descriptor-hash-list has been
renamed to auto-revert--buffers-by-watch-descriptors. This small patch
averts an ancaught error.
=> fix auto-revert-notify var name for emacs 27

request.el
generally though inotifies regenerate on their own.
addressing some of alphapapa's concerns in #132
=> avoid killing inotifies in all buffers

request.el, tests/test-request.el, tests/testserver.py
Emacs 26.3, Ubuntu 18.04.1
Without that fix, Emacs interprets curl output as utf-8-dos and strips all \r .
It results in an error `(search-failed "^\r\n")`,
when moving from "100 Continue" to the next one in `request--goto-next-body`.
It's kind of strange behavior of Emacs,
since there is a single newline after the body:
```
body\n
(:num-redirects 0 :url-effective "http://127.0.0.1:60079/longtextline")
```
From the docs:
>Emacs recognizes which kind of end-of-line conversion to use based on the
contents of the file: if it sees only carriage returns, or only carriage return
followed by linefeed sequences, then it chooses the end-of-line conversion accordingly.
This behavior only manifests itself when body is a single long line.
Alternative solutions:
Use `inhibit-eol-conversion` somehow. …
=> Add fix for an edge case (with a test) involving "100 Continue" and long body

Makefile, request.el, tests/testserver.py
Commit 1562f9c seems to conflate the desire to encode request data in
utf8 with also decoding server output.
In light of #157 and #158, I am removing utf-8 decoding altogether.
The impetus to encode to utf-8 in #77, #85, and
org-trello/org-trello#340 suggest nothing about also decoding in utf-8,
so I am crossing my fingers I won't rebreak for them.
Also, clean up logging.  It was impossible to follow with all the
capital letters.
=> Encoding is not decoding

request.el
Currently, `request` indented like below.
```emacs-lisp
(request
url
...)
(request url
...)
```
But this patch merged, indented like below.
``` emacs-lisp
(request
url
...)
(request url
...)
```
```
=> Indent request like defun

request.el
#159 is broking #157. Getting `Got error: (search-failed "^\r\n")`
By removing the line `(set-process-coding-system proc encoding encoding)`  and change encoding back to `utf-8` from `utf-8-unix` , the carriage return will also automatically being removed by Emacs automatically encoding/decoding process. 
This make very long body request become broken, especially in Windows since its `default-process-coding-system` is set to `(utf-8-dos . utf-8-unix)`.
In the light of #158, it seems that most `request` dependent packages doesn't aware of that and do not properly decode the response output and assume that they will always receiving `utf-8` decoded data.
I think that we should add additional parameter `decoding` so we can separate `curl` output decoding from the global …
=> Adding decoding option for response

.gitmodules
This is especially important for users without ssh access.
=> Use the same protocol for submodule

request.el
Between curl 7.44 and 7.66, curl's behavior under --include changed.
Explicitly avoid --include with file URLs.
Closes #164
=> Fully deal with file URLs

request.el
inotify continues to lock emacs under global-auto-revert-mode.
Force kill inotify watchers under curl-sync (they will regenerate on their
own).
=> Revert #152

request.el, tests/test-request.el
@ndw rather than keying off host and port, perhaps it'd be more natural just to key off host?
it'd also be nice to have emacs prompt the user if the auth entry is missing.
=> Auth digest

tests/testserver.py
The /redirect handler on the test Flask server is meant to redirect
/redirect/foo/bar to /foo/bar, and the tests expect that behavior (for
example, request-get-simple-redirection assumes a chain of
/redirect/redirect/report/some-path -> /redirect/report/some-path ->
/report/some-path).
Instead, /redirect/foo/bar actually redirects to /redirect/foo/bar/foo/bar,
because the /redirect handler returns redirect(path), and Werkzeug's response
wrapper resolves non-absolute Location headers relative to the incoming
request's full URL.
This change prepends a "/" to the paramter to redirect(), casuing Werkzeug
to fix the Location header as intended, and fixing
request-get-simple-redirection.
=> testserver.py: redirect to correct path

tests/testserver.py
PR #179 fixed the /redirect handler to redirect to abolute paths.  This change
makes the same fix to other handlers (/cookies, /login, /logout, and /sleep).
This fixes the request-simple-cookie and request-multiple-cookies tests.
=> testserver.py: fix redirects from handlers besides /redirect.

tests/test-request.el
This test invokes request-testing-with-response-slots but has no body to
actually use the response slots; all the test assertions are in the
response-producing form.  Removing the macro invocation eliminates a
byte-compilation error.
=> remove spurious with-response-slots from request-auth test

request.el
Hide those `Contacting host: localhost:8080` messages on every request, matching the behavior with the curl backend. I don't think there's a good reason to make this configurable.
If you're wondering why I'm using the `url-retrieve` backend at all, it seems synchronous curl is still quite slow as detailed in https://github.com/tkf/emacs-request/issues/5. In fact it seems to get 0.3 seconds added on to each request, and deleting the `0.3` from line 1244 does seem to make it run 300ms faster (though still not as fast as `url-retrieve`), though I didn't look to see if this would break anything outside my own use case.
=> Use url-retrieve silently

request.el, tests/test-request.el
Prevent cURL from burping an error when making HEAD requests.
=> Head requests

tests/test-request.el
This is to avoid a use-before-definition warning -- the variable was
referenced in a test earlier in the file than its definition.
=> Move definition of request-testing-server-name to top of file

README.rst
Thanks for maintaining this package!
I fix README S-exp format as `(declare (indent 1))`
=> Fix README S-exp format as (declare (indent 1))

request.el
Found an issue with request where it was ignoring the value of `:mime-type` when specified.
For example, this:
```emacs-lisp
(request-response-data
(request "http://httpbin.org/post"
:type "POST"
:files `(("test" . ("file" :file "/home/ryan/hello.txt" :mime-type "text/plain")))
:parser 'json-read
:success (cl-function
(lambda (&key data &allow-other-keys)
(message "data %s" data)))))
```
would generate a `--form` flag like: `test=@/home/ryan/hello.txt;filename=file`. This patch fixes the code such that `type=...` is added.
=> fixes issue with missing mime-types

request.el
To reproduce, have emacs built with native compilation and notice the compilation logs. You can then open the offending file and run `M-x emacs-lisp-native-compile-and-load` before and after the changes to see the warning is removed.
```
request.el:817:25: Warning: ‘point’ is an obsolete generalized variable; use
‘goto-char’ instead.
request.el:822:25: Warning: ‘point’ is an obsolete generalized variable; use
‘goto-char’ instead.
```
=> Fix emacs native compilation warning

.github/workflows/test.yml, Makefile, request.el
Okay so this is a very nuanced enhancement.
So `curl(1)`  says in the section about the `--form` flag:
> To force the 'content' part to be a file, prefix the file name with an @ sign. To just get the content part from a file, prefix the file name with the symbol <. The difference between @ and < is then that @ makes a file get attached in the post as a file upload, while the < makes a text field and just get the contents for that text field from a file.
Consider the difference between:
```bash
echo 'hello world' | curl https://httpbin.org/post -F "request=@-;" 
```
and
```bash
echo 'hello world' | curl https://httpbin.org/post -F "request=<-;" 
```
Before this PR, request by default sends all files using `@`. By specifying `:use-contents t` when uploading a file, it'll generate the curl …
=> adds support for curl "<"
