request.el
=> Fixed parameter ordering in assoc-string calls

request.el
- Add `:type` attribute to customize variables
- Remove needless sentence
=> Refactoring

request.el
Hello!
With very little modification emacs-request now supports TRAMP! This is useful when you want your requests to be run on the remote host you're currently on, which is my case.
The first hunk could probably be made prettier, 99% of the trick is simply calling `start-file-process` instead of `start-process`... but I had to modify the first hunk because it explicitely changed default-directory to `~/`, effectively forcing it to execute on the local machine instead of the remote one.
If the default-directory manipulation is not that important, we could envisage to completely remove it. It was introduced by 584338027cfd6033ba95330483e646afeea75dfa.
=> Support TRAMP

README.rst
Cherry-pick #45 commit and format better style.
=> Better formatting #45.

README.rst
=> Use syntax highlight for code examples

doc/source/manual.rst
=> Fix documentation typo

request.el
This is related to #51.
CC: @NOBUTOKA
=> Stringify 'value' of alist same as 'key'

request.el
httponly cookie starts with '#' but it is not comment line in cookie-jar
file of curl.
This is related to #60.
=> Fix parser for httponly cookie

request.el, tests/test-request.el
=> Support optional curl options

request.el
https://github.com/tkf/emacs-request/pull/68#discussion_r96869924
=> Improve curl option variable comment

.travis.yml
=> fix obsolete EMACS_EVM value

tests/testserver.py
=> fix testserver for python3

.travis.yml, request.el
Under curl backend, the `request--curl-callback` will take care of
calling `request--callback`, and `request-response--timeout-callback`
should not do it again!
=> Fixes #115

request.el, tests/request-testing.el, tests/test-request.el
Rebasing #119 onto development.  Did not know how to directly rebase someone else's PR.
=> Fix reference to err variable

request.el
While we still heavy-handedly default the encoding to utf-8, we fall
back to no-conversion if that assumption fails (rather than allowing
`select-safe-coding-system` to bring up a confusing dialogue).
Closes #77
=> Fall back to no-conversion if utf-8 fails

request.el, tests/test-request.el
=> Test PR #127

README.rst
=> Document sync flag

README.rst
=> Warn users of default encoding

request.el
Try start-process instead of start-file-process to head off louietan's
inotify descriptor.
=> A pure guess: inotify

request.el
Issue #132 persists even after faulty fixes #140 and #141.  This time
knockout all inotify's in all buffers!
=> Really fix deadlock

request.el, tests/test-request.el
Also, modify skeeto/elfeed code to be exactly like his (forego
any stylistic edits, e.g. setf gethash versus puthash, to immediately
remove any doubts by future readers of the code).
=> Test curl capabilities code

.travis.yml, request.el
One should not remove hashtable entries while iterating over it.
=> autorevert iterable bug

Makefile, tests/request-testing.el, tools/install-cask.sh
=> Avoid global-auto-revert-mode

request.el
Add headers slot into request-response structure
Before this patch, we can use `request-response-header` and
`request-response--raw-header`, but I want to know all headers
well structured.
Now, we can use `request-response-headers` to get well structured headers.
Sample.
```elisp
(request "http://httpbin.org/get"
:params '(("key" . "value") ("key2" . "value2"))
:parser 'json-read
:success (cl-function
(lambda (&key data &allow-other-keys)
(message "I sent: %S" (assoc-default 'args data))))
:complete (cl-function
(lambda (&key response &allow-other-keys)
(with-current-buffer (get-buffer-create "*request*")
(erase-buffer)
(insert (pp-to-string response))
(newline)
(insert (pp-to-string (request-response--raw-header response)))
(newline) (newline)
(insert (pp-to-string …
```
=> Add headers slot into request-response structure

.github/workflows/test.yml, request.el
add autoload cookies to functions and macro-defined functions
I'm not completly sure, if this is the correct way, and if I have addressed the complete external api; but it would be a start.
=> autoload cookies for api functions

.github/workflows/test.yml, Makefile, request.el
Getting test-install to grok a *non-owner amended* cross-repo pull request is too complex.
=> Autoloads (was #217)

.github/workflows/test.yml, request.el
=> Cslux data alist not converted
